name: Dependabot Merge
inputs:
  repo:
    default: ${{ github.repository }}
  pull:
    default: ${{ github.event.number }}
  token:
    default: ${{ secrets.PAT }}
if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
run: |
  curl -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: token ${{ inputs.token }}" \
    -d "{\"body\": \"@dependabot merge\"}" \
    "https://api.github.com/repos/${{ inputs.repo }}/issues/${{ inputs.pull }}/comments"
